### ISSUE TITLE
Multiple monitor support

### ISSUE THREAD

**Issue by matiassingers** [sindresorhus/macos-wallpaper#2]
Currently it'll only report back the "primary" monitor wallpaper:

``` objc
forScreen:[NSScreen mainScreen]
```

---

Not that's it's super important, but just wanted to bring it up :wink:

**Comment by sindresorhus** [comment]
Yeah, intentional, I considered it, but didn't want to complicate the first release with it. If support were to be added, how would you want it to work? Should the image be duplicated on every screen? Or would you want to choose an unique image for each screen?

**Comment by matiassingers** [comment]
@sindresorhus good question!
The behavior using the GUI is to set separate wallpaper for each monitor, I however realise that this complicates the CLI considerably.

One approach could be: create flag for setting nth-monitor specifically: `--second`, and then handle no flag case:
1. sets all monitors to same wallpaper
2. sets only primary

----

But I think you are right, it might complicate things too much - especially considering Linux and Windows platforms.
How does the GUI on these platforms handle it?

**Comment by ben-eb** [comment]
:+1:

I'd like a flag that could just set all desktops to one image - but I think it would be good to keep the default behaviour as only affecting the current desktop, as that mimics how the GUI works on OS X.

**Comment by petecoop** [comment]
:+1:

I'd like this functionality too - but it would be very nice to be able to specify different images for each monitor. This also only affects the current Desktop whereas you might have a few desktops per screen also.

**Comment by Zinglish** [comment]
I implemented my own multiscreen support if anyone was interested: https://github.com/Zinglish/osx-wallpaper/tree/multiscreen. Just waiting for sindresorhus to accept the pull request :)

**Comment by benniemosher** [comment]
What is the status of this? I am using this package in a personal project and would love to be able to support multiple screens.

**Comment by Zinglish** [comment]
Well, my implementation works (see my comment above) but the creators are giving me shit about my standards so they refuse to merge it into their code. Which is fair enough really, I just have to sort my crap out but haven't had time to do so.

**Comment by andypotts** [comment]
:+1: I would also find this really useful for a personal project.

**Comment by blackthroat** [comment]
There is definitely still interest in this feature.

**Comment by FinnGu** [comment]
Would still like to see this feature 👍

**Comment by andypotts** [comment]
🎉

**Comment by FinnGu** [comment]
Can't wait to try it out :heart_eyes:

**Comment by sindresorhus** [comment]
2.0.0 is out: https://github.com/sindresorhus/macos-wallpaper/releases/tag/v2.0.0
