### ISSUE TITLE
Support for cocoapods

### ISSUE THREAD

**Issue by tapkain** [sindresorhus/macos-wallpaper#21]
Is there a reason why the lib is not published as pod package? By the way a useful library 👍

**Comment by sindresorhus** [comment]
Sorry, I'm not interested in supporting CocoaPods in tiny libs like this. It comes with too much overhead, both in having to maintain a boilerplaty podfile and having to commit the whole Xcode project. The future is SPM and there's nothing stopping you from using both or just copy-paste the source here into your project. It's not much and it won't change much either.
