### ISSUE TITLE
Unable to build as part of Xcode Project

### ISSUE THREAD

**Issue by WeebLabs** [sindresorhus/macos-wallpaper#22]
For reasons that I don't quite comprehend, adding this package to any Xcode project results in a "Missing required module 'SQLiteObjc" error.

I am very new to Swift but am fairly certain that I have imported all of the required frameworks correctly.  This had initially been working but since rebuilding my project due to an Xcode crash, I have been unable to replicate my earlier success.  I have tried re-creating the project on other machines, which yields the same error.

Thus far, I have tried:

- Generated Xcode project for Wallpaper via "swift package generate-xcodeproj --xcconfig-overrides=Config.xcconfig".
- Added Wallpaper project to main Xcode project and linked all four libraries to the target.
- Added Wallpaper frameworks directly to main project folder and linked.
- Switched to Swift 4.2.0.
- Switched to Xcode 10.0.

Attached are screenshots of my current project configuration.
![image](https://user-images.githubusercontent.com/8558544/50912078-2e07f980-1429-11e9-88b4-9642ecdd9f45.png)

![image](https://user-images.githubusercontent.com/8558544/50912116-437d2380-1429-11e9-94d2-0a733f45af1c.png)

![image](https://user-images.githubusercontent.com/8558544/50912150-5db70180-1429-11e9-85d9-52e54c215a4a.png)

**Comment by sindresorhus** [comment]
You might have to add the `SQLite` (or `SQLiteObjc`) framework to "Linked Frameworks and Libraries" in Xcode.

**Comment by Haru-tan** [comment]
As you can see from the screenshots above, I have linked both frameworks to the project targets (and earlier to the Wallpaper.xcodeproj file) but the error persists.  At the moment, the library is sporadically working in a random test project but I have stepped through every configurable setting or path and the main project is identical in every respect.

I am using three other frameworks in my main project without issue, so this is rather puzzling.

**Comment by Haru-tan** [comment]
The issue appears to pertain to the SQLite wrapper fetched when building Wallpaper.  Downloading, building the wrapper separately and then adding it to my main project has allowed me to build successfully.
