### ISSUE TITLE
Is it possible to use this feature in a macOS app?

### ISSUE THREAD

**Issue by pradeepb28** [sindresorhus/macos-wallpaper#37]
Is it possible to use this library in a macOS app built on Appkit/SwiftUI?

Usecase: Able to change the wallpaper of macOS from mac app.

Thank you

**Comment by sindresorhus** [comment]
Yes, it is clearly documented in the readme. See the API section.

**Comment by pradeepb28** [comment]
sorry I missed it somehow, thank you
