### ISSUE TITLE
Case if the wallpaper is set to change every X minutes.

### ISSUE THREAD

**Issue by musically-ut** [sindresorhus/macos-wallpaper#7]
If I set my Desktop wallpaper settings to:

 - [x] Change picture: `Every X minutes`
 - [x] Random Order

this binary only gives me a path to the folder instead of the currently active file:

```
➔  ./wallpaper
/Users/musically_ut/Pictures
```
----

I had to resort to some hackery to get the actual active wallpaper: [musically-ut/WhichBG](https://github.com/musically-ut/WhichBG). However, I don't know how to map the correct wallpaper to the correct screen/desktop in that setting.

**Comment by sindresorhus** [comment]
Known issue: https://github.com/sindresorhus/wallpaper/issues/4

**Comment by musically-ut** [comment]
So what do you think about the hack of reading the sqlite3 DB to [figure out all the valid filenames which could be wallpapers](https://github.com/musically-ut/whichbg/blob/master/WhichBG/DesktopPictureViewController.swift#L37)?

That certainly doesn't use the blessed API and there doesn't seem to be a good way of working around the issue?

**Comment by sindresorhus** [comment]
Looked into this again, and this AppleScript snippet seems to work even when the wallpaper is set to change on an interval:

```applescript
tell application "System Events" to picture of current desktop
```

I guess we could fall back to that if what's returned from the native API is a directory?

**Comment by sindresorhus** [comment]
Radar: https://openradar.appspot.com/radar?id=4959084113559552
